### Basic Checks

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("car_evaluation.csv")
df

     buying  maint  doors  persons lug_boot safety outcome
0     vhigh  vhigh      2        2    small    low   unacc
1     vhigh  vhigh      2        2    small    med   unacc
2     vhigh  vhigh      2        2    small   high   unacc
3     vhigh  vhigh      2        2      med    low   unacc
4     vhigh  vhigh      2        2      med    med   unacc
...     ...    ...    ...      ...      ...    ...     ...
1723    low    low      5        5      med    med    good
1724    low    low      5        5      med   high   vgood
1725    low    low      5        5      big    low   unacc
1726    low    low      5        5      big    med    good
1727    low    low      5        5      big   high   vgood

[1728 rows x 7 columns]

In [3]:
df.tail()

     buying maint  doors  persons lug_boot safety outcome
1723    low   low      5        5      med    med    good
1724    low   low      5        5      med   high   vgood
1725    low   low      5        5      big    low   unacc
1726    low   low      5        5      big    med    good
1727    low   low      5        5      big   high   vgood

In [4]:
df.head()

  buying  maint  doors  persons lug_boot safety outcome
0  vhigh  vhigh      2        2    small    low   unacc
1  vhigh  vhigh      2        2    small    med   unacc
2  vhigh  vhigh      2        2    small   high   unacc
3  vhigh  vhigh      2        2      med    low   unacc
4  vhigh  vhigh      2        2      med    med   unacc

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   int64
 3   persons   1728 non-null   int64
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   outcome   1728 non-null   object
dtypes: int64(2), object(5)
memory usage: 94.6+ KB

In [6]:
df.describe()

             doors      persons
count  1728.000000  1728.000000
mean      3.500000     3.666667
std       1.118358     1.247580
min       2.000000     2.000000
25%       2.750000     2.000000
50%       3.500000     4.000000
75%       4.250000     5.000000
max       5.000000     5.000000

In [7]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
outcome     0
dtype: int64

### value_count()

In [8]:
df.buying.value_counts()

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

In [9]:
df.maint.value_counts()

maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

In [10]:
df.lug_boot.value_counts()

lug_boot
small    576
med      576
big      576
Name: count, dtype: int64

In [11]:
df.safety.value_counts()

safety
low     576
med     576
high    576
Name: count, dtype: int64

In [12]:
df.outcome.value_counts()

outcome
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

### Encoding

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Buying"]=le.fit_transform(df.buying)

In [14]:
df.head()

  buying  maint  doors  persons lug_boot safety outcome  Buying
0  vhigh  vhigh      2        2    small    low   unacc       3
1  vhigh  vhigh      2        2    small    med   unacc       3
2  vhigh  vhigh      2        2    small   high   unacc       3
3  vhigh  vhigh      2        2      med    low   unacc       3
4  vhigh  vhigh      2        2      med    med   unacc       3

In [15]:
df.buying.value_counts()

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

In [16]:
df["buying"]=le.fit_transform(df.buying)
df["maint"]=le.fit_transform(df.maint)
df["lug_boot"]=le.fit_transform(df.lug_boot)
df["safety"]=le.fit_transform(df.safety)

In [17]:
df.head()

   buying  maint  doors  persons  lug_boot  safety outcome  Buying
0       3      3      2        2         2       1   unacc       3
1       3      3      2        2         2       2   unacc       3
2       3      3      2        2         2       0   unacc       3
3       3      3      2        2         1       1   unacc       3
4       3      3      2        2         1       2   unacc       3

In [18]:
df.maint.value_counts()

maint
3    432
0    432
2    432
1    432
Name: count, dtype: int64

In [19]:
df.lug_boot.value_counts()

lug_boot
2    576
1    576
0    576
Name: count, dtype: int64

In [20]:
df.safety.value_counts()

safety
1    576
2    576
0    576
Name: count, dtype: int64

In [21]:
df

      buying  maint  doors  persons  lug_boot  safety outcome  Buying
0          3      3      2        2         2       1   unacc       3
1          3      3      2        2         2       2   unacc       3
2          3      3      2        2         2       0   unacc       3
3          3      3      2        2         1       1   unacc       3
4          3      3      2        2         1       2   unacc       3
...      ...    ...    ...      ...       ...     ...     ...     ...
1723       1      1      5        5         1       2    good       1
1724       1      1      5        5         1       0   vgood       1
1725       1      1      5        5         0       1   unacc       1
1726       1      1      5        5         0       2    good       1
1727       1      1      5        5         0       0   vgood       1

[1728 rows x 8 columns]

In [22]:
df["outcome"]=le.fit_transform(df.outcome)

In [23]:
df

      buying  maint  doors  persons  lug_boot  safety  outcome  Buying
0          3      3      2        2         2       1        2       3
1          3      3      2        2         2       2        2       3
2          3      3      2        2         2       0        2       3
3          3      3      2        2         1       1        2       3
4          3      3      2        2         1       2        2       3
...      ...    ...    ...      ...       ...     ...      ...     ...
1723       1      1      5        5         1       2        1       1
1724       1      1      5        5         1       0        3       1
1725       1      1      5        5         0       1        2       1
1726       1      1      5        5         0       2        1       1
1727       1      1      5        5         0       0        3       1

[1728 rows x 8 columns]

### Outlier Detecting

* checking outliers for numerical columns(outliers are identified only in numerical cols)

In [24]:
df.persons.value_counts()

persons
2    576
4    576
5    576
Name: count, dtype: int64

In [25]:
df.doors.value_counts()

doors
2    432
3    432
4    432
5    432
Name: count, dtype: int64

* Insight-since there is no huge difference among data points...no outliers are present

### Random Forest 
* finite data..since there are less values..if more values..then linear regression

In [26]:
df

      buying  maint  doors  persons  lug_boot  safety  outcome  Buying
0          3      3      2        2         2       1        2       3
1          3      3      2        2         2       2        2       3
2          3      3      2        2         2       0        2       3
3          3      3      2        2         1       1        2       3
4          3      3      2        2         1       2        2       3
...      ...    ...    ...      ...       ...     ...      ...     ...
1723       1      1      5        5         1       2        1       1
1724       1      1      5        5         1       0        3       1
1725       1      1      5        5         0       1        2       1
1726       1      1      5        5         0       2        1       1
1727       1      1      5        5         0       0        3       1

[1728 rows x 8 columns]

In [27]:
X=df.iloc[:,:-1]
y=df.outcome

In [28]:
##train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [29]:
##model creation
from sklearn.ensemble import RandomForestClassifier  ##this is our new model.
model = RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [30]:
##model evalution
from sklearn.metrics import accuracy_score, classification_report
y_pred = model.predict(X_test)
accuracy_score(y_pred,y_test)

1.0

In [31]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        80
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00       236
           3       1.00      1.00      1.00        14

    accuracy                           1.00       346
   macro avg       1.00      1.00      1.00       346
weighted avg       1.00      1.00      1.00       346

In [32]:
#save after training the model
import joblib
joblib.dump(model,"random_forest_model.pkl")

['random_forest_model.pkl']

In [35]:
import gradio as gr
import joblib
import numpy as np

# Load model trained on 7 features
model = joblib.load("random_forest_model.pkl")

# Define prediction function
def predict_car_safety(buying, maint, doors, persons, lug_boot, safety, dummy_class):
    input_data = np.array([[int(buying), int(maint), int(doors), int(persons), int(lug_boot), int(safety), int(dummy_class)]])
    prediction = model.predict(input_data)[0]
    return f"Prediction Outcome: {prediction}"

# Gradio input components for 7 features (last is a dummy placeholder for class)
inputs = [
    gr.Dropdown([0, 1, 2, 3], label="Buying (0:high, 1:low, 2:med, 3:vhigh)"),
    gr.Dropdown([0, 1, 2, 3], label="Maintenance (0:high, 1:low, 2:med, 3:vhigh)"),
    gr.Dropdown([0, 1, 2, 3], label="Doors (0:2, 1:3, 2:4, 3:5more)"),
    gr.Dropdown([0, 1, 2], label="Persons (0:2, 1:4, 2:more)"),
    gr.Dropdown([0, 1, 2], label="Lug Boot Size (0:big, 1:med, 2:small)"),
    gr.Dropdown([0, 1, 2], label="Safety (0:high, 1:low, 2:med)"),
    gr.Dropdown([0, 1, 2, 3], label="Dummy Class Input (0:unacc, 1:acc, 2:good, 3:vgood)")
]

# Launch Gradio app
gr.Interface(
    fn=predict_car_safety,
    inputs=inputs,
    outputs="text",
    title="Car Evaluation (7-Feature Input)",
    description="⚠️ This interface uses 7 inputs as expected by your trained model. The 7th is a placeholder for the class label and is not recommended in production."
).launch()

* Running on local URL:  http://127.0.0.1:7862
* To create a public link, set `share=True` in `launch()`.